[package]
name = "tools-index"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@google.com>"]

[[bin]]
name = "run"
path = "src/bin/run.rs"

[dependencies]
log = "0.3.8"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_yaml = "0.7.1"
